language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: square-developers
  on:
    branch: master
    repo: square/square-python-sdk
  password:
    secure: X4Q0hnzT68VD134x/Buub2uQbeZWRYEXi7BFy3tjrcfTj1jspf6hh37kXxtFkDpWXMVuzALP3CWh03+QpdrHdHn6JWMInaH63B9cVIDhK6V0kHXU81KorKJE4DkoNVhHT9qWzxmqPoV8QNIx2++Yo73wnoyEyMfxStLxDpfODhsjb8u4A7irkCg0ecw9XAQ9eTHzRe2goqBPfyPx9J3yPd7X/DgbQ+4lLFpvBGVK4VZNlmGfEB2iPWQe22HTftRkqG3+/b7ETDDYSZlRvudgUyNjgO5IWec1jlhwwPcXVZ/861bRpULlug6yUQtQKFu3KAjP3dCrKWz2t9UkFI1sp0LC76PxdAvYioIKtBSZEEYJ0SjV/GGPGFkFMmJJzs113nLg76iwSMlvXHaF2x0vfGLh0o14DUR9Pm4fy3uq1LgLEo8BMdhfl5KMKiDhgR/0dxXYAf6sZa0TnbbFyJK/vr6GSm8CeGtRt7y15uN20ia57MIL93PsJwsBGFA9QFOUT43BtjqVPD59llWR3opRk1ub4o7Bt8bubTxOAwU1q3NwQC5zZPb/XrdJ9AEkSrA5F0amE5lwF5IsvU8ZrEjy3NSgaBH63Zj1NWivZHgl/nJ7yvUCBq1YujLcudlSakFzE/uwjrekCcearB/lnVFOFgX3pdpB3VXO1Mu2eyckOP4=
  skip_existing: true
env:
  global:
    secure: ZCiFzWx69EVLAqklrXec52FXDK4brooa2NT6gXz+VXfaowKyZ1WaJh48AXF7lNEjCW1imQDJ3fJaPz8mxI+MwwZ2e8g2lCXC+jhedNNy72/oS2nqdzmO71adMSMDJuUBSWH6CfWiKhf79MazjhRIJB6JGOPiScTFmzBq2LD1/eOfLIQVmXqsGqnF0YsLFj7MyI/PJmASqtJWSYQkTmVVMGTVr1/7KQgVlaXwAdFQOUQwHzJCDIbdw3zZFP8+qBLkzNNP1yXn40J4cHn/OslcQCS5kcL3TwZ5iXOASk8IcrjF0cIj7/+/UXREKHppJSMwx/zafiSB5BWWGhRSNuWAm2/Jdl1vb37LiKWbbXhNWk/5DJrnD5lrGJWtR7sh7fPKORXojaputakhOAMlLq9lCqt5nZjkR59Q+zU+oLPD7elbbjbfXz6UOAxt24jTHQ/bUV075EWz1p8/Sc5ocdV4Xf6GbogQ63bDPu3+F7dWRcbNIaUaDsDCoOV5HmclfmoD0ovyDNtuXTWIeZGNPHuJXFi+zSTOFciNBsPQ8UvO2/ybw/UQ97QT78wt08+ZFGhzlOddQD45liBZmbDIT7CJIBiU/zdNXx81Qeiu+LnFrpynseFf9gYPhxid5ivW8he3L0X6enxLNZ9pMXyqUcrNZj4nhtA4OHcxG+0btQXHI6Y=
notifications:
  slack:
    secure: Gh641zg9Ch+sFZCWwxdi6ZPQk1csUGcwenfL9cgs3op+BfQOJbBgw3LWGqYVBBgTowO8ibg/q/kapzg9lGjLxQOVNPQZci7dFB5WHmdVwUoSoLxQCZcCa0IQkk0XfI7UYKBnuoqpBsEe6eXKyvdFEUrx51Z4XwFtjLpINYZ4DY2NmsA9QihFJBSqhB4si7l0yON2Q8JR4Dc6PXCLn+LrzNliHCgzWveF/FtRQocT4uj3e3frySdOHmb6fV2yGb8Z/jR01s/97cyX6Y37BWyGrZFTfyDb+V5lcAzJdgkYhLaeLo8coKwZwgWOu6Eo6EeQ4/Y/XKr9BjdKmyWY0Z2gc4FPWrHvfrGdUsSfr2ECdApMsNcNPeTtvAc2xe8wDVbASLdrg5pcZCba5PZBgZ4KvQ7Rg7olo9dbHRbUddy0VFM1Td9heBKXV9gL1bkv1eLMa400uGKoA6A7lim8AkjEBTiLQ3pZOalZGDUop5iDD8pmnwZ9rd51LI03hSIrC75j1ePlqxwQ6z6R2xjwCHznNveiI/CQGtLr4vMuexGG//afK8/WGlnVch+CpEkC/aEok/0L3ik3l6OgfXuHItgY3SrUny18uYNQK4NXPo+PT+m82qzSONpHxhdkYXsz8GP5/Rn5v2wUShLUKwU/EKi20fjcI1jO/JAW8gcJAwfBChA=
  on_success: change
    template:
      - "@oncall"
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
  email:
    recipients:
      - dexteam-external@squareup.com
    on_success: change
